version: '3'

services: 
# Collector
  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/conf/otel-collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel/otel-collector-config.yaml:/conf/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
    networks:
      - testapp-nw

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - testapp-nw

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - testapp-nw

  otel-agent:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-agent-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel/otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250:14250"       # Jaeger grpc receiver
      - "14268:14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
    depends_on:
      - otel-collector
    networks:
      - testapp-nw

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./otel/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - testapp-nw    
networks:
  testapp-nw:
    driver: bridge
