scrape_configs:
  #- job_name: 'otel-collector'
  - job_name: "demo_quarkus"
    scrape_interval: 10s
    metrics_path: "/q/metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]
      #- targets: ['otel-collector:8889']
      #- targets: ['otel-collector:8888']

#remote_write:
 # - url: http://victoriametrics:8428/api/v1/write